"""Add Review and Rating tables

Revision ID: 7e355faf0ca8
Revises: c5ef79f4575d
Create Date: 2024-10-18 17:07:13.117346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e355faf0ca8'
down_revision: Union[str, None] = 'c5ef79f4575d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
